apiVersion: networking.gke.io/v1
kind: GCPGatewayPolicy
metadata:
  name: global-access-policy
  namespace: gateway
spec:
  default:
    allowGlobalAccess: true
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: internal-http