apiVersion: v1
kind: Service
metadata:
  name: whereami-service-a-neg
  namespace: service-a
  annotations:
    cloud.google.com/neg: '{"exposed_ports": {"80":{"name": "whereami-service-a-neg"}}}'
spec:
  type: ClusterIP
  selector:
    app: whereami-service-a
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080