apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: service-b-health-check
  namespace: service-b
spec:
  default:
    config:
      httpHealthCheck:
        port: 8080
        portSpecification: USE_FIXED_PORT
        requestPath: /
      type: HTTP
  targetRef:
    group: ""
    kind: Service
    name: whereami-service-b